name: Backdate Commits
on:
  workflow_dispatch:

jobs:
  fix-date:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Change Last Commit Date
        run: |
          git config user.name "Nathaniel Coronado"
          git config user.email "nathaniel.coronado@neu.edu.ph"
          # Papalitan nito ang huling commit date sa April 27
          git commit --amend --no-edit --date="2026-04-27T10:00:00"
          git push origin main --force
